<a href="https://colab.research.google.com/github/ricartorres/Educacion/blob/main/Tarea_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea 1 - Introducción al análisis de datos: *Python* y *NumPy***


In [ ]:
import numpy as np

In [ ]:
!python --version
print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.21.6


In [ ]:
# CELDA DE PRUEBAS 
a = np.array([0, 5, 1, 2, 3])

b = np.array(
  [[2, 0, 2, 1, 4],
  [1, 5, 1, 0, 1],
  [3, 2, 0, 0, 1],
  [2, 2, 0, 2, 1]]  
)

c=np.multiply(a, b)
#print(c.shape[0])
i=0
conteos=np.zeros(c.shape[0]+1)
for item in c:
    #print(c[i].sum())
    conteos[i]=c[i].sum()
    i=i+1
    
print(conteos)    

[16. 29. 13. 17.  0.]


## **1. Conteo de pedidos**


In [ ]:
# FUNCIÓN CALIFICADA: conteo_pedidos(pedidos)
def conteo_pedidos(pedidos):
  """
  pedidos: un arreglo de NumPy con valores enteros no negativos. Contiene IDs de productos pedidos, pueden estar repetidos.

  Retorna un arreglo con el conteo de los IDs del arreglo de pedidos. 
  El arreglo resultante codifica cada conteo en su posición de ID correspondiente.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 6 líneas de código
  
  # Obtenga el valor máximo del arreglo 'pedidos'
  máximo = pedidos.max()

  # Calcule el tamaño del arreglo resultante 
  pedidosOrganizados=np.unique(pedidos)
  tamaño = pedidosOrganizados.size
  
  # Cree un arreglo de ceros con ese tamaño para la guardar su respuesta
  conteos=np.zeros(máximo+1)

  for item in pedidosOrganizados:
      conteos[item] = np.count_nonzero(pedidos == item)
  

  # Recorra cada ID en el arreglo de 'pedidos' e incremente en 1 la cantidad 
  # correspondiente a ese ID en el arreglo de 'conteos' en cada iteración

  ### FIN DEL CÓDIGO ###

  return conteos

In [ ]:
# CELDA DE PRUEBAS 
print(conteo_pedidos(np.array([1, 2, 3, 3, 3, 5, 5, 6])))

print(conteo_pedidos(np.array([2, 2, 3, 4])))

print(conteo_pedidos(np.array([1, 2, 3])))

[0. 1. 1. 3. 0. 2. 1.]
[0. 0. 2. 1. 1.]
[0. 1. 1. 1.]


In [ ]:
#[0. 0. 4. 1. 1.]
print(conteo_pedidos(np.array([2, 2, 3, 4, 2, 2])))

#[0. 1. 1. 1.]
print(conteo_pedidos(np.array([1, 2, 3])))

#[1.]
print(conteo_pedidos(np.array([0])))
#print(conteo_pedidos(np.array([201, 2, 3, 24, 2, 2, 5, 2 , 2 , 2 , 2 , 2 , 14, 6, 1, 3])))


[0. 0. 4. 1. 1.]
[0. 1. 1. 1.]
[1.]


## **2. Cantidad de material**


In [ ]:
# FUNCIÓN CALIFICADA: cantidad_material(productos, cantidades)
def cantidad_material(productos, cantidades):
  """
  productos: un arreglo de NumPy con dimensión (n,) con valores enteros no negativos.
             Contiene la cantidad pedida de cada uno de los productos.
  cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
              Contiene las unidades de materia prima (filas) necesarias para la 
              fabricación de cada producto (columnas)

  Retorna un arreglo con dimensión (m,) con la cantidad de unidades de materia prima 
  requeridas en el pedido.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 1-5 líneas de código
  
  # Opere las matrices de entrada para obtener el valor requerido.
  # Tenga en cuenta la dimensión de los arreglos a la hora de realizar las operaciones
  #materiales = None
  ### FIN DEL CÓDIGO ###
  
  c=np.multiply(productos, cantidades)
  
  i=0
  materiales=np.zeros(c.shape[0])
  for item in c:
      materiales[i]=c[i].sum()
      i=i+1
  return materiales

In [ ]:
# CELDA DE PRUEBAS 
productos = np.array([0, 5, 1, 2])

cantidades = np.array(
  [[2, 0, 2, 1,],
  [1, 5, 1, 0],
  [3, 2, 0, 0],
  [2, 2, 0, 2]]  
)

cantidad_material(productos, cantidades)

array([ 4., 26., 10., 14.])

In [ ]:
productos = np.array([2, 5, 7, 8])
cantidades = np.array(
    [[2, 0, 2, 1,],
    [1, 1, 1, 0],
    [2, 2, 0, 2]]  
  )
cantidad_material(productos, cantidades)

array([26., 14., 30.])

## **3. Cálculo de costos**


In [ ]:
# FUNCIÓN CALIFICADA: costo_pedido(pedidos, cantidades, costos, descuento, lote)
def costo_pedido(pedidos, cantidades, costos, descuento, lote):
  """
  pedidos: un arreglo de NumPy con valores enteros no negativos entre 0 y n - 1.
  cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
  costos: un arreglo de NumPy con dimensión (m, ) con valores reales no negativos.
  descuento: un número real entre 0.0 y 1.0
  lote: un número entero no negativo.

  Retorna un número real no negativo con el costo total del pedido.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###  
  # Reemplace la palabra None por el código correspondiente
  # ~ 5-7 líneas de código

  productos = conteo_pedidos(pedidos) # Genere el arreglo de conteo de productos.
  materiales = cantidad_material(productos, cantidades) # Genere el arreglo de cantidad de unidades por material.
  costos_pedido = np.multiply(materiales, costos) # Opere las matrices para obtener el costo total por material.

  # Realice la operación de descuento utilizando la condición de lote mínimo.
  i=0
  for item in materiales:
      if (materiales[i]>=lote):
         costos_pedido[i]=(costos_pedido[i]-(costos_pedido[i]*descuento))
      i=i+1
      
  costo_total = costos_pedido.sum() # Calcule el costo total del pedido con los descuentos aplicados.
  ### FIN DEL CÓDIGO ###
  return costo_total

In [ ]:
# CELDA DE PRUEBAS 
pedidos = np.array([0, 0, 1, 2, 2, 2, 2])
cantidades = np.array(
    [[2, 3, 2],
    [1, 5, 1]]  
  )
costos = np.array([5.0, 3.0])

costo_pedido(pedidos, cantidades, costos, 0.2, 15)
#93

93.0

In [ ]:
# CELDA DE PRUEBAS 
pedidos = np.array([0, 0, 1, 2, 2, 2, 2, 2, 3])
cantidades = np.array(
      [[2, 0, 2, 1,],
      [1, 1, 1, 0],
      [2, 2, 0, 2]]  
    )

costos = np.array([5.0, 3.0, 4.5])

costo_pedido(pedidos, cantidades, costos, 0.1, 5)
#121.5

121.5